name: Sync issues
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Sync request"
        required: false
        default: "All"

env:
  GITHUB_TOKEN: ${{ secrets.ISSUE_SYNC_TOKEN }}

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: Maximisch/issue-sync-action
        with:
          repo_target: "MixedRealityToolkit/MixedRealityToolkit-Unity" # The target repository
          only_sync_on_label: "MRTK3" # Only syncs issues with this label set
          only_sync_main_issue: false # Excludes comments