name: sync-issues

on:
  workflow_dispatch:
  push:
  issues:
    types:
      [
        opened,
        deleted,
        transferred,
        closed,
        reopened,
        assigned,
        unassigned,
        labeled,
        unlabeled,
      ]

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c60a92eb51acca2de954c3fe8ff9b67de265c56f
      - name: sync
        uses: ./issues_sync_action
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_SYNC_TOKEN }}
        with:
          repo_target: "MixedRealityToolkit/MixedRealityToolkit-Unity" # The target repository
          only_sync_on_label: "MRTK3" # Only syncs issues with this label set
          only_sync_main_issue: false # Excludes comments